apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: a6pvk8mzg-go 
  janus-idp.io/tekton: a6pvk8mzg-go
  backstage.io/kubernetes-id: a6pvk8mzg-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: a6pvk8mzg-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml